TOPLEVEL_LANG = verilog
VERILOG_SOURCES = mux4way16.v ../nand/nand.v ../not/not.v ../and/and.v ../or/or.v \
				  ../mux/mux.v ../mux16/mux16.v
TOPLEVEL = mux_4_way_16
MODULE = mux4way16_test
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
