TOPLEVEL_LANG = verilog
VERILOG_SOURCES = mux.v ../nand/nand.v ../not/not.v ../and/and.v ../or/or.v
TOPLEVEL = mux_2
MODULE = mux_test
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
