TOPLEVEL_LANG = verilog
VERILOG_SOURCES = demux.v ../nand/nand.v ../not/not.v ../and/and.v ../or/or.v
TOPLEVEL = demux_2
MODULE = demux_test
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
