TOPLEVEL_LANG = verilog
VERILOG_SOURCES = mux16.v ../nand/nand.v ../not/not.v ../and/and.v ../or/or.v ../mux/mux.v
TOPLEVEL = mux_16
MODULE = mux16_test
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
