TOPLEVEL_LANG = verilog
VERILOG_SOURCES = or16.v ../nand/nand.v ../not/not.v ../and/and.v ../or/or.v
TOPLEVEL = or_16
MODULE = or16_test
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
