TOPLEVEL_LANG = verilog
VERILOG_SOURCES = xor.v ../nand/nand.v ../and/and.v ../or/or.v ../not/not.v
TOPLEVEL = xor_2
MODULE = xor_test
SIM = icarus

include $(shell cocotb-config --makefiles)/Makefile.sim
