name: CI

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up Icarus Verilog
        run: sudo apt-get install -y iverilog

      - name: Set up cocotb
        run: python3 -m pip install cocotb

      - name: Run tests
        run: make
